import { StyleSheet } from 'react-native';

import { colors, radius, shadow, spacing } from './theme';

export const componentStyles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  shellScroll: {
    flexGrow: 1,
    padding: spacing.lg,
    gap: spacing.lg,
  },
  shellContent: {
    gap: spacing.lg,
  },
  heroHaloTop: {
    position: 'absolute',
    top: -100,
    right: -70,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: 'rgba(20, 184, 166, 0.18)',
  },
  heroHaloBottom: {
    position: 'absolute',
    bottom: -120,
    left: -100,
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(15, 118, 110, 0.12)',
  },
  heroCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    overflow: 'hidden',
    ...shadow,
  },
  heroTag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    marginBottom: spacing.md,
  },
  heroTagText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    marginBottom: spacing.xs,
  },
  heroSubtitle: {
    color: colors.textSoft,
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.md,
    ...shadow,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
  },
  cardSubtitle: {
    color: colors.textSoft,
    fontSize: 14,
    lineHeight: 20,
  },
  row: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  button: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.primary,
  },
  buttonSecondary: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.surfaceSoft,
    borderWidth: 1,
    borderColor: 'rgba(15, 118, 110, 0.16)',
  },
  buttonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
  buttonTextSecondary: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: '700',
  },
  inputGroup: {
    gap: 8,
  },
  label: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  input: {
    minHeight: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#f7fffe',
    color: colors.text,
    paddingHorizontal: spacing.md,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 96,
    textAlignVertical: 'top',
    paddingTop: 14,
  },
  helperText: {
    color: colors.textSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  chip: {
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    backgroundColor: colors.surfaceSoft,
  },
  chipText: {
    color: colors.primaryDark,
    fontWeight: '700',
    fontSize: 13,
  },
  statTile: {
    flex: 1,
    minWidth: '46%',
    borderRadius: radius.md,
    padding: spacing.md,
    backgroundColor: '#f6fffe',
    borderWidth: 1,
    borderColor: 'rgba(15, 118, 110, 0.12)',
    gap: 8,
  },
  statValue: {
    color: colors.primaryDark,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '800',
  },
  statLabel: {
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  emptyState: {
    paddingVertical: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyStateText: {
    color: colors.textSoft,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
});